---
- name: bcwork update deploy staging
  hosts: workstg
#  become: true
#  become_user: root
#  become_method: sudo
  tasks:
    - name: Copy bcwork
      ansible.builtin.copy:
        src: bcwork
        dest: /usr/local/bin/bcwork
        owner: root
        mode: '0755'

    - name: start bcwork-api
      ansible.builtin.service:
              name: bcwork-api
              state: restarted
