# More info on config here: https://golangci-lint.run/usage/configuration/#config-file
run:
  concurrency: 8
  timeout: 10m
  issues-exit-code: 1
  tests: true

output:
  formats: 
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  goconst:
    min-len:         2
    min-occurrences: 2
  staticcheck:
    checks:
      - '-SA1019'
  nlreturn:
    block-size: 2

linters:
  disable-all: true
  enable:
    # - errcheck
    # - goconst
    # - goimports
    # - gosec
    # - govet
    # - ineffassign
    # - gosimple
    # - staticcheck
    # - revive
    # - typecheck
    - unused
    - whitespace
    - nlreturn
    # - errorlint

issues:
  exclude-use-default: false
  exclude:
    - G104
    - exported func .* returns unexported type .*, which can be annoying to use
    - should have a package comment
    - don't use an underscore in package name
    # EXC0001 errcheck: Almost all programs ignore errors on these functions and in most cases it's ok
    - Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Rollback|.*BindPFlag|.*Listen|.*Commit|.*Flush|os\.Remove(All)?|.*print(f|ln)?|os\.(Un)?Setenv). is not checked
    - should check returned error before deferring
    - should check error returned from os.Create() before deferring file.Close()
    - (break|continue) with no blank line before
  exclude-dirs:
    - models
  max-issues-per-linter: 0
  max-same-issues: 0
