
ALTER TABLE factor
ALTER COLUMN domain SET NOT NULL,
ALTER COLUMN country SET NOT NULL,
ALTER COLUMN device SET NOT NULL,
ALTER COLUMN browser SET NOT NULL,
ALTER COLUMN os SET NOT NULL,
ALTER COLUMN placement_type SET NOT NULL;

ALTER TABLE factor
ADD CONSTRAINT fk_factor_publisher
FOREIGN KEY (publisher) REFERENCES publisher(publisher_id) ON DELETE CASCADE;

ALTER TABLE factor
DROP CONSTRAINT factor_pkey;

ALTER TABLE factor
ADD PRIMARY KEY (rule_id);
