ALTER TABLE floor
    ALTER COLUMN country DROP NOT NULL,
ALTER COLUMN device DROP NOT NULL,
ALTER COLUMN placement_type DROP NOT NULL,
ALTER COLUMN os DROP NOT NULL,
ALTER COLUMN browser DROP NOT NULL;
