package core

var DemandPartnerMap = map[string]string{
	"33across":                   "33Across",
	"adaptmx":                    "AdaptMX",
	"adyoulike-oms":              "Adyoulike OMS",
	"amazon":                     "Amazon",
	"appnexus":                   "AppNexus",
	"appnexus-tailwind":          "AppNexusTailwind",
	"index-pbs":                  "Index Latam",
	"onemobile-audienciad-yahoo": "OneMobile",
	"onemobile-bcm":              "OneMobile BCM",
	"onetag-bcm":                 "Onetag BCM",
	"onetag-audienciad":          "Onetag Audienciad",
	"openx":                      "OpenX",
	"openx-pbs":                  "OpenX",
	"pubmatic-pbs":               "Pubmatic BCM",
	"pubmatic-sahar":             "Pubmatic Sahar",
	"pulsepoint-bcm":             "pulsepoint bcm",
	"rubicon":                    "Rubicon",
	"rubicon-getmedia":           "RubiconGetMedia",
	"rubicon-sahar":              "Rubicon Sahar",
	"sonobi-bcm":                 "Sonobi BCM",
	"sovrn":                      "Sovrn BCM",
	"smaato-limpid":              "Smaato Limpid",
	"adyoulike-pbs":              "Adyoulike",
	"brightcom":                  "Brightcom",
	"smart-getmedia-pbs":         "SmartGetMedia",
	"smart-limpid":               "SmartLimp",
	"conversant-pbs":             "ConversantOno",
	"yieldmo-audienciad":         "Yieldmo",
	"yieldmo-ono":                "Yieldmo Ono",
	"sharethrough-bcm":           "Sharethrough BCM",
	"loopme-bcm":                 "Loopme",
	"loopme-oms":                 "LoopMe OMS",
	"unruly-oms":                 "Unruly OMS",
	"medianet-bcm":               "Medianet BCM",
	"appnexusia":                 "Appnexus IA",
	"sharethrough-ono":           "Sharethrough Ono",
	"richaudience":               "Richaudience",
	"appnexusbcm":                "AppNexus BCM",
	"s2ssharethroughbcm":         "Sharethrough Bcm",
	"smaatolimpid":               "Smaato limpid",
	"criteo":                     "Criteo",
}
