name: Deploy-bcWork

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22.2

      - name: Verify dependencies
        run: go mod verify

      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: Verify Ansible installation
        run: ansible --version

      - name: Install dependencies
        run: |
          go version
          go get -u golang.org/x/lint/golint

      - name: Build
        run: go build -v ./...

      - name: Updating Swag doc
        run: go get -u github.com/swaggo/swag/cmd/swag

#      - name: Run tests
#        run:  go test ./...

      - name: Build
        run: |
          GOOS=linux GOARCH=amd64 go build -o bcwork main.go
          if [ $? -eq 0 ]; then
            echo "bcwork build success"
          else
            echo "bcwork build failed" >&2
            exit 1
          fi

      - name: Move Build to Deploy Directory
        run: mv bcwork deploy/ansible/files/

      - name: Run Ansible Playbook
        run: ansible-playbook -vvvv deploy/ansible/bcwork_update.yml -i deploy/ansible/brightcom_hosts --user root
