name: Deploy-bcWork

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22.2

      - name: Verify dependencies
        run: go mod verify

      - name: Install dependencies
        run: |
          go version
          go get -u golang.org/x/lint/golint

      - name: Build
        run: go build -v ./...

      - name: Updating Swag doc
        run: go get -u github.com/swaggo/swag/cmd/swag

#      - name: Run go vet & lint
#        run: |
#          go vet .
#          golint .

#      - name: Install staticcheck
#        run: go install honnef.co/go/tools/cmd/staticcheck@latest

#      - name: Run staticcheck
#        run: staticcheck ./...

#      - name: Run tests
#        run: go api/rest && go test -v
