name: test

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-22.04
    services:
      dind:
        image: docker:27.3-dind-rootless
        ports:
          - 2375:2375

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22.2

      - name: Build
        run: go build -v ./...
  
      - name: Test
        run:  go test -v $(go list ./... | grep -v /models)
