// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testAdsTXTS(t *testing.T) {
	t.Parallel()

	query := AdsTXTS()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testAdsTXTSDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AdsTXT{}
	if err = randomize.Struct(seed, o, adsTXTDBTypes, true, adsTXTColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AdsTXT struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := AdsTXTS().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testAdsTXTSQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AdsTXT{}
	if err = randomize.Struct(seed, o, adsTXTDBTypes, true, adsTXTColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AdsTXT struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := AdsTXTS().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := AdsTXTS().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testAdsTXTSSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AdsTXT{}
	if err = randomize.Struct(seed, o, adsTXTDBTypes, true, adsTXTColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AdsTXT struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := AdsTXTSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := AdsTXTS().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testAdsTXTSExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AdsTXT{}
	if err = randomize.Struct(seed, o, adsTXTDBTypes, true, adsTXTColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AdsTXT struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := AdsTXTExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if AdsTXT exists: %s", err)
	}
	if !e {
		t.Errorf("Expected AdsTXTExists to return true, but got false.")
	}
}

func testAdsTXTSFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AdsTXT{}
	if err = randomize.Struct(seed, o, adsTXTDBTypes, true, adsTXTColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AdsTXT struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	adsTXTFound, err := FindAdsTXT(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if adsTXTFound == nil {
		t.Error("want a record, got nil")
	}
}

func testAdsTXTSBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AdsTXT{}
	if err = randomize.Struct(seed, o, adsTXTDBTypes, true, adsTXTColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AdsTXT struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = AdsTXTS().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testAdsTXTSOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AdsTXT{}
	if err = randomize.Struct(seed, o, adsTXTDBTypes, true, adsTXTColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AdsTXT struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := AdsTXTS().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testAdsTXTSAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	adsTXTOne := &AdsTXT{}
	adsTXTTwo := &AdsTXT{}
	if err = randomize.Struct(seed, adsTXTOne, adsTXTDBTypes, false, adsTXTColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AdsTXT struct: %s", err)
	}
	if err = randomize.Struct(seed, adsTXTTwo, adsTXTDBTypes, false, adsTXTColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AdsTXT struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = adsTXTOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = adsTXTTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := AdsTXTS().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testAdsTXTSCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	adsTXTOne := &AdsTXT{}
	adsTXTTwo := &AdsTXT{}
	if err = randomize.Struct(seed, adsTXTOne, adsTXTDBTypes, false, adsTXTColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AdsTXT struct: %s", err)
	}
	if err = randomize.Struct(seed, adsTXTTwo, adsTXTDBTypes, false, adsTXTColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AdsTXT struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = adsTXTOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = adsTXTTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := AdsTXTS().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func adsTXTBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *AdsTXT) error {
	*o = AdsTXT{}
	return nil
}

func adsTXTAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *AdsTXT) error {
	*o = AdsTXT{}
	return nil
}

func adsTXTAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *AdsTXT) error {
	*o = AdsTXT{}
	return nil
}

func adsTXTBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *AdsTXT) error {
	*o = AdsTXT{}
	return nil
}

func adsTXTAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *AdsTXT) error {
	*o = AdsTXT{}
	return nil
}

func adsTXTBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *AdsTXT) error {
	*o = AdsTXT{}
	return nil
}

func adsTXTAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *AdsTXT) error {
	*o = AdsTXT{}
	return nil
}

func adsTXTBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *AdsTXT) error {
	*o = AdsTXT{}
	return nil
}

func adsTXTAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *AdsTXT) error {
	*o = AdsTXT{}
	return nil
}

func testAdsTXTSHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &AdsTXT{}
	o := &AdsTXT{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, adsTXTDBTypes, false); err != nil {
		t.Errorf("Unable to randomize AdsTXT object: %s", err)
	}

	AddAdsTXTHook(boil.BeforeInsertHook, adsTXTBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	adsTXTBeforeInsertHooks = []AdsTXTHook{}

	AddAdsTXTHook(boil.AfterInsertHook, adsTXTAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	adsTXTAfterInsertHooks = []AdsTXTHook{}

	AddAdsTXTHook(boil.AfterSelectHook, adsTXTAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	adsTXTAfterSelectHooks = []AdsTXTHook{}

	AddAdsTXTHook(boil.BeforeUpdateHook, adsTXTBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	adsTXTBeforeUpdateHooks = []AdsTXTHook{}

	AddAdsTXTHook(boil.AfterUpdateHook, adsTXTAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	adsTXTAfterUpdateHooks = []AdsTXTHook{}

	AddAdsTXTHook(boil.BeforeDeleteHook, adsTXTBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	adsTXTBeforeDeleteHooks = []AdsTXTHook{}

	AddAdsTXTHook(boil.AfterDeleteHook, adsTXTAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	adsTXTAfterDeleteHooks = []AdsTXTHook{}

	AddAdsTXTHook(boil.BeforeUpsertHook, adsTXTBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	adsTXTBeforeUpsertHooks = []AdsTXTHook{}

	AddAdsTXTHook(boil.AfterUpsertHook, adsTXTAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	adsTXTAfterUpsertHooks = []AdsTXTHook{}
}

func testAdsTXTSInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AdsTXT{}
	if err = randomize.Struct(seed, o, adsTXTDBTypes, true, adsTXTColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AdsTXT struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := AdsTXTS().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testAdsTXTSInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AdsTXT{}
	if err = randomize.Struct(seed, o, adsTXTDBTypes, true); err != nil {
		t.Errorf("Unable to randomize AdsTXT struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(adsTXTColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := AdsTXTS().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testAdsTXTToOneDemandPartnerChildUsingDemandPartnerChild(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local AdsTXT
	var foreign DemandPartnerChild

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, adsTXTDBTypes, true, adsTXTColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AdsTXT struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, demandPartnerChildDBTypes, false, demandPartnerChildColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DemandPartnerChild struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	queries.Assign(&local.DemandPartnerChildID, foreign.ID)
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.DemandPartnerChild().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if !queries.Equal(check.ID, foreign.ID) {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	ranAfterSelectHook := false
	AddDemandPartnerChildHook(boil.AfterSelectHook, func(ctx context.Context, e boil.ContextExecutor, o *DemandPartnerChild) error {
		ranAfterSelectHook = true
		return nil
	})

	slice := AdsTXTSlice{&local}
	if err = local.L.LoadDemandPartnerChild(ctx, tx, false, (*[]*AdsTXT)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.DemandPartnerChild == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.DemandPartnerChild = nil
	if err = local.L.LoadDemandPartnerChild(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.DemandPartnerChild == nil {
		t.Error("struct should have been eager loaded")
	}

	if !ranAfterSelectHook {
		t.Error("failed to run AfterSelect hook for relationship")
	}
}

func testAdsTXTToOneDemandPartnerConnectionUsingDemandPartnerConnection(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local AdsTXT
	var foreign DemandPartnerConnection

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, adsTXTDBTypes, true, adsTXTColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AdsTXT struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, demandPartnerConnectionDBTypes, false, demandPartnerConnectionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DemandPartnerConnection struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	queries.Assign(&local.DemandPartnerConnectionID, foreign.ID)
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.DemandPartnerConnection().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if !queries.Equal(check.ID, foreign.ID) {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	ranAfterSelectHook := false
	AddDemandPartnerConnectionHook(boil.AfterSelectHook, func(ctx context.Context, e boil.ContextExecutor, o *DemandPartnerConnection) error {
		ranAfterSelectHook = true
		return nil
	})

	slice := AdsTXTSlice{&local}
	if err = local.L.LoadDemandPartnerConnection(ctx, tx, false, (*[]*AdsTXT)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.DemandPartnerConnection == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.DemandPartnerConnection = nil
	if err = local.L.LoadDemandPartnerConnection(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.DemandPartnerConnection == nil {
		t.Error("struct should have been eager loaded")
	}

	if !ranAfterSelectHook {
		t.Error("failed to run AfterSelect hook for relationship")
	}
}

func testAdsTXTToOnePublisherUsingPublisher(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local AdsTXT
	var foreign Publisher

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, adsTXTDBTypes, false, adsTXTColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AdsTXT struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, publisherDBTypes, false, publisherColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Publisher struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.PublisherID = foreign.PublisherID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.Publisher().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.PublisherID != foreign.PublisherID {
		t.Errorf("want: %v, got %v", foreign.PublisherID, check.PublisherID)
	}

	ranAfterSelectHook := false
	AddPublisherHook(boil.AfterSelectHook, func(ctx context.Context, e boil.ContextExecutor, o *Publisher) error {
		ranAfterSelectHook = true
		return nil
	})

	slice := AdsTXTSlice{&local}
	if err = local.L.LoadPublisher(ctx, tx, false, (*[]*AdsTXT)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Publisher == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.Publisher = nil
	if err = local.L.LoadPublisher(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Publisher == nil {
		t.Error("struct should have been eager loaded")
	}

	if !ranAfterSelectHook {
		t.Error("failed to run AfterSelect hook for relationship")
	}
}

func testAdsTXTToOneSeatOwnerUsingSeatOwner(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local AdsTXT
	var foreign SeatOwner

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, adsTXTDBTypes, true, adsTXTColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AdsTXT struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, seatOwnerDBTypes, false, seatOwnerColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SeatOwner struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	queries.Assign(&local.SeatOwnerID, foreign.ID)
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.SeatOwner().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if !queries.Equal(check.ID, foreign.ID) {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	ranAfterSelectHook := false
	AddSeatOwnerHook(boil.AfterSelectHook, func(ctx context.Context, e boil.ContextExecutor, o *SeatOwner) error {
		ranAfterSelectHook = true
		return nil
	})

	slice := AdsTXTSlice{&local}
	if err = local.L.LoadSeatOwner(ctx, tx, false, (*[]*AdsTXT)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.SeatOwner == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.SeatOwner = nil
	if err = local.L.LoadSeatOwner(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.SeatOwner == nil {
		t.Error("struct should have been eager loaded")
	}

	if !ranAfterSelectHook {
		t.Error("failed to run AfterSelect hook for relationship")
	}
}

func testAdsTXTToOneSetOpDemandPartnerChildUsingDemandPartnerChild(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a AdsTXT
	var b, c DemandPartnerChild

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, adsTXTDBTypes, false, strmangle.SetComplement(adsTXTPrimaryKeyColumns, adsTXTColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, demandPartnerChildDBTypes, false, strmangle.SetComplement(demandPartnerChildPrimaryKeyColumns, demandPartnerChildColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, demandPartnerChildDBTypes, false, strmangle.SetComplement(demandPartnerChildPrimaryKeyColumns, demandPartnerChildColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*DemandPartnerChild{&b, &c} {
		err = a.SetDemandPartnerChild(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.DemandPartnerChild != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.AdsTXTS[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if !queries.Equal(a.DemandPartnerChildID, x.ID) {
			t.Error("foreign key was wrong value", a.DemandPartnerChildID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.DemandPartnerChildID))
		reflect.Indirect(reflect.ValueOf(&a.DemandPartnerChildID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if !queries.Equal(a.DemandPartnerChildID, x.ID) {
			t.Error("foreign key was wrong value", a.DemandPartnerChildID, x.ID)
		}
	}
}

func testAdsTXTToOneRemoveOpDemandPartnerChildUsingDemandPartnerChild(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a AdsTXT
	var b DemandPartnerChild

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, adsTXTDBTypes, false, strmangle.SetComplement(adsTXTPrimaryKeyColumns, adsTXTColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, demandPartnerChildDBTypes, false, strmangle.SetComplement(demandPartnerChildPrimaryKeyColumns, demandPartnerChildColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err = a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = a.SetDemandPartnerChild(ctx, tx, true, &b); err != nil {
		t.Fatal(err)
	}

	if err = a.RemoveDemandPartnerChild(ctx, tx, &b); err != nil {
		t.Error("failed to remove relationship")
	}

	count, err := a.DemandPartnerChild().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 0 {
		t.Error("want no relationships remaining")
	}

	if a.R.DemandPartnerChild != nil {
		t.Error("R struct entry should be nil")
	}

	if !queries.IsValuerNil(a.DemandPartnerChildID) {
		t.Error("foreign key value should be nil")
	}

	if len(b.R.AdsTXTS) != 0 {
		t.Error("failed to remove a from b's relationships")
	}
}

func testAdsTXTToOneSetOpDemandPartnerConnectionUsingDemandPartnerConnection(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a AdsTXT
	var b, c DemandPartnerConnection

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, adsTXTDBTypes, false, strmangle.SetComplement(adsTXTPrimaryKeyColumns, adsTXTColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, demandPartnerConnectionDBTypes, false, strmangle.SetComplement(demandPartnerConnectionPrimaryKeyColumns, demandPartnerConnectionColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, demandPartnerConnectionDBTypes, false, strmangle.SetComplement(demandPartnerConnectionPrimaryKeyColumns, demandPartnerConnectionColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*DemandPartnerConnection{&b, &c} {
		err = a.SetDemandPartnerConnection(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.DemandPartnerConnection != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.AdsTXTS[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if !queries.Equal(a.DemandPartnerConnectionID, x.ID) {
			t.Error("foreign key was wrong value", a.DemandPartnerConnectionID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.DemandPartnerConnectionID))
		reflect.Indirect(reflect.ValueOf(&a.DemandPartnerConnectionID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if !queries.Equal(a.DemandPartnerConnectionID, x.ID) {
			t.Error("foreign key was wrong value", a.DemandPartnerConnectionID, x.ID)
		}
	}
}

func testAdsTXTToOneRemoveOpDemandPartnerConnectionUsingDemandPartnerConnection(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a AdsTXT
	var b DemandPartnerConnection

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, adsTXTDBTypes, false, strmangle.SetComplement(adsTXTPrimaryKeyColumns, adsTXTColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, demandPartnerConnectionDBTypes, false, strmangle.SetComplement(demandPartnerConnectionPrimaryKeyColumns, demandPartnerConnectionColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err = a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = a.SetDemandPartnerConnection(ctx, tx, true, &b); err != nil {
		t.Fatal(err)
	}

	if err = a.RemoveDemandPartnerConnection(ctx, tx, &b); err != nil {
		t.Error("failed to remove relationship")
	}

	count, err := a.DemandPartnerConnection().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 0 {
		t.Error("want no relationships remaining")
	}

	if a.R.DemandPartnerConnection != nil {
		t.Error("R struct entry should be nil")
	}

	if !queries.IsValuerNil(a.DemandPartnerConnectionID) {
		t.Error("foreign key value should be nil")
	}

	if len(b.R.AdsTXTS) != 0 {
		t.Error("failed to remove a from b's relationships")
	}
}

func testAdsTXTToOneSetOpPublisherUsingPublisher(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a AdsTXT
	var b, c Publisher

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, adsTXTDBTypes, false, strmangle.SetComplement(adsTXTPrimaryKeyColumns, adsTXTColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, publisherDBTypes, false, strmangle.SetComplement(publisherPrimaryKeyColumns, publisherColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, publisherDBTypes, false, strmangle.SetComplement(publisherPrimaryKeyColumns, publisherColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*Publisher{&b, &c} {
		err = a.SetPublisher(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.Publisher != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.AdsTXTS[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.PublisherID != x.PublisherID {
			t.Error("foreign key was wrong value", a.PublisherID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.PublisherID))
		reflect.Indirect(reflect.ValueOf(&a.PublisherID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.PublisherID != x.PublisherID {
			t.Error("foreign key was wrong value", a.PublisherID, x.PublisherID)
		}
	}
}
func testAdsTXTToOneSetOpSeatOwnerUsingSeatOwner(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a AdsTXT
	var b, c SeatOwner

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, adsTXTDBTypes, false, strmangle.SetComplement(adsTXTPrimaryKeyColumns, adsTXTColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, seatOwnerDBTypes, false, strmangle.SetComplement(seatOwnerPrimaryKeyColumns, seatOwnerColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, seatOwnerDBTypes, false, strmangle.SetComplement(seatOwnerPrimaryKeyColumns, seatOwnerColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*SeatOwner{&b, &c} {
		err = a.SetSeatOwner(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.SeatOwner != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.AdsTXTS[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if !queries.Equal(a.SeatOwnerID, x.ID) {
			t.Error("foreign key was wrong value", a.SeatOwnerID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.SeatOwnerID))
		reflect.Indirect(reflect.ValueOf(&a.SeatOwnerID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if !queries.Equal(a.SeatOwnerID, x.ID) {
			t.Error("foreign key was wrong value", a.SeatOwnerID, x.ID)
		}
	}
}

func testAdsTXTToOneRemoveOpSeatOwnerUsingSeatOwner(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a AdsTXT
	var b SeatOwner

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, adsTXTDBTypes, false, strmangle.SetComplement(adsTXTPrimaryKeyColumns, adsTXTColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, seatOwnerDBTypes, false, strmangle.SetComplement(seatOwnerPrimaryKeyColumns, seatOwnerColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err = a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = a.SetSeatOwner(ctx, tx, true, &b); err != nil {
		t.Fatal(err)
	}

	if err = a.RemoveSeatOwner(ctx, tx, &b); err != nil {
		t.Error("failed to remove relationship")
	}

	count, err := a.SeatOwner().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 0 {
		t.Error("want no relationships remaining")
	}

	if a.R.SeatOwner != nil {
		t.Error("R struct entry should be nil")
	}

	if !queries.IsValuerNil(a.SeatOwnerID) {
		t.Error("foreign key value should be nil")
	}

	if len(b.R.AdsTXTS) != 0 {
		t.Error("failed to remove a from b's relationships")
	}
}

func testAdsTXTSReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AdsTXT{}
	if err = randomize.Struct(seed, o, adsTXTDBTypes, true, adsTXTColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AdsTXT struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testAdsTXTSReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AdsTXT{}
	if err = randomize.Struct(seed, o, adsTXTDBTypes, true, adsTXTColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AdsTXT struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := AdsTXTSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testAdsTXTSSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AdsTXT{}
	if err = randomize.Struct(seed, o, adsTXTDBTypes, true, adsTXTColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AdsTXT struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := AdsTXTS().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	adsTXTDBTypes = map[string]string{`ID`: `integer`, `DemandPartnerConnectionID`: `integer`, `DemandPartnerChildID`: `integer`, `SeatOwnerID`: `integer`, `PublisherID`: `character varying`, `Domain`: `character varying`, `Status`: `character varying`, `DemandStatus`: `character varying`, `DomainStatus`: `character varying`, `CreatedAt`: `timestamp without time zone`, `UpdatedAt`: `timestamp without time zone`, `StatusChangedAt`: `timestamp without time zone`, `LastScannedAt`: `timestamp without time zone`, `ErrorMessage`: `character varying`, `Retries`: `integer`, `ValidURL`: `character varying`}
	_             = bytes.MinRead
)

func testAdsTXTSUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(adsTXTPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(adsTXTAllColumns) == len(adsTXTPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &AdsTXT{}
	if err = randomize.Struct(seed, o, adsTXTDBTypes, true, adsTXTColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AdsTXT struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := AdsTXTS().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, adsTXTDBTypes, true, adsTXTPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize AdsTXT struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testAdsTXTSSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(adsTXTAllColumns) == len(adsTXTPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &AdsTXT{}
	if err = randomize.Struct(seed, o, adsTXTDBTypes, true, adsTXTColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AdsTXT struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := AdsTXTS().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, adsTXTDBTypes, true, adsTXTPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize AdsTXT struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(adsTXTAllColumns, adsTXTPrimaryKeyColumns) {
		fields = adsTXTAllColumns
	} else {
		fields = strmangle.SetComplement(
			adsTXTAllColumns,
			adsTXTPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := AdsTXTSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testAdsTXTSUpsert(t *testing.T) {
	t.Parallel()

	if len(adsTXTAllColumns) == len(adsTXTPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := AdsTXT{}
	if err = randomize.Struct(seed, &o, adsTXTDBTypes, true); err != nil {
		t.Errorf("Unable to randomize AdsTXT struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert AdsTXT: %s", err)
	}

	count, err := AdsTXTS().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, adsTXTDBTypes, false, adsTXTPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize AdsTXT struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert AdsTXT: %s", err)
	}

	count, err = AdsTXTS().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
