// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

// TestToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestToOne(t *testing.T) {
	t.Run("BidCachingToPublisherUsingBidCachingPublisher", testBidCachingToOnePublisherUsingBidCachingPublisher)
	t.Run("ConfiantToPublisherUsingPublisher", testConfiantToOnePublisherUsingPublisher)
	t.Run("DemandParnterPlacementToDemandPartnerUsingDemandPartner", testDemandParnterPlacementToOneDemandPartnerUsingDemandPartner)
	t.Run("DemandPartnerChildToDpoUsingDPParent", testDemandPartnerChildToOneDpoUsingDPParent)
	t.Run("DemandPartnerConnectionToDpoUsingDemandPartner", testDemandPartnerConnectionToOneDpoUsingDemandPartner)
	t.Run("DpoToUserUsingManager", testDpoToOneUserUsingManager)
	t.Run("DpoRuleToDpoUsingDemandPartner", testDpoRuleToOneDpoUsingDemandPartner)
	t.Run("DpoRuleToPublisherUsingDpoRulePublisher", testDpoRuleToOnePublisherUsingDpoRulePublisher)
	t.Run("FactorToPublisherUsingFactorPublisher", testFactorToOnePublisherUsingFactorPublisher)
	t.Run("FloorToPublisherUsingFloorPublisher", testFloorToOnePublisherUsingFloorPublisher)
	t.Run("PixalateToPublisherUsingPublisher", testPixalateToOnePublisherUsingPublisher)
	t.Run("PublisherDemandToDpoUsingDemandPartner", testPublisherDemandToOneDpoUsingDemandPartner)
	t.Run("PublisherDemandToPublisherUsingPublisher", testPublisherDemandToOnePublisherUsingPublisher)
	t.Run("PublisherDomainToPublisherUsingPublisher", testPublisherDomainToOnePublisherUsingPublisher)
	t.Run("RefreshCacheToPublisherUsingRefreshCachePublisher", testRefreshCacheToOnePublisherUsingRefreshCachePublisher)
	t.Run("SellersJSONHistoryToCompetitorUsingCompetitorNameCompetitor", testSellersJSONHistoryToOneCompetitorUsingCompetitorNameCompetitor)
	t.Run("TargetingToPublisherUsingPublisher", testTargetingToOnePublisherUsingPublisher)
}

// TestOneToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOne(t *testing.T) {
	t.Run("CompetitorToSellersJSONHistoryUsingCompetitorNameSellersJSONHistory", testCompetitorOneToOneSellersJSONHistoryUsingCompetitorNameSellersJSONHistory)
}

// TestToMany tests cannot be run in parallel
// or deadlocks can occur.
func TestToMany(t *testing.T) {
	t.Run("DemandPartnerToDemandParnterPlacements", testDemandPartnerToManyDemandParnterPlacements)
	t.Run("DpoToDPParentDemandPartnerChildren", testDpoToManyDPParentDemandPartnerChildren)
	t.Run("DpoToDemandPartnerDemandPartnerConnections", testDpoToManyDemandPartnerDemandPartnerConnections)
	t.Run("DpoToDemandPartnerDpoRules", testDpoToManyDemandPartnerDpoRules)
	t.Run("DpoToDemandPartnerPublisherDemands", testDpoToManyDemandPartnerPublisherDemands)
	t.Run("PublisherToBidCachings", testPublisherToManyBidCachings)
	t.Run("PublisherToConfiants", testPublisherToManyConfiants)
	t.Run("PublisherToDpoRules", testPublisherToManyDpoRules)
	t.Run("PublisherToFactors", testPublisherToManyFactors)
	t.Run("PublisherToFloors", testPublisherToManyFloors)
	t.Run("PublisherToPixalates", testPublisherToManyPixalates)
	t.Run("PublisherToPublisherDemands", testPublisherToManyPublisherDemands)
	t.Run("PublisherToPublisherDomains", testPublisherToManyPublisherDomains)
	t.Run("PublisherToRefreshCaches", testPublisherToManyRefreshCaches)
	t.Run("PublisherToTargetings", testPublisherToManyTargetings)
	t.Run("UserToManagerDpos", testUserToManyManagerDpos)
}

// TestToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneSet(t *testing.T) {
	t.Run("BidCachingToPublisherUsingBidCachings", testBidCachingToOneSetOpPublisherUsingBidCachingPublisher)
	t.Run("ConfiantToPublisherUsingConfiants", testConfiantToOneSetOpPublisherUsingPublisher)
	t.Run("DemandParnterPlacementToDemandPartnerUsingDemandParnterPlacements", testDemandParnterPlacementToOneSetOpDemandPartnerUsingDemandPartner)
	t.Run("DemandPartnerChildToDpoUsingDPParentDemandPartnerChildren", testDemandPartnerChildToOneSetOpDpoUsingDPParent)
	t.Run("DemandPartnerConnectionToDpoUsingDemandPartnerDemandPartnerConnections", testDemandPartnerConnectionToOneSetOpDpoUsingDemandPartner)
	t.Run("DpoToUserUsingManagerDpos", testDpoToOneSetOpUserUsingManager)
	t.Run("DpoRuleToDpoUsingDemandPartnerDpoRules", testDpoRuleToOneSetOpDpoUsingDemandPartner)
	t.Run("DpoRuleToPublisherUsingDpoRules", testDpoRuleToOneSetOpPublisherUsingDpoRulePublisher)
	t.Run("FactorToPublisherUsingFactors", testFactorToOneSetOpPublisherUsingFactorPublisher)
	t.Run("FloorToPublisherUsingFloors", testFloorToOneSetOpPublisherUsingFloorPublisher)
	t.Run("PixalateToPublisherUsingPixalates", testPixalateToOneSetOpPublisherUsingPublisher)
	t.Run("PublisherDemandToDpoUsingDemandPartnerPublisherDemands", testPublisherDemandToOneSetOpDpoUsingDemandPartner)
	t.Run("PublisherDemandToPublisherUsingPublisherDemands", testPublisherDemandToOneSetOpPublisherUsingPublisher)
	t.Run("PublisherDomainToPublisherUsingPublisherDomains", testPublisherDomainToOneSetOpPublisherUsingPublisher)
	t.Run("RefreshCacheToPublisherUsingRefreshCaches", testRefreshCacheToOneSetOpPublisherUsingRefreshCachePublisher)
	t.Run("SellersJSONHistoryToCompetitorUsingCompetitorNameSellersJSONHistory", testSellersJSONHistoryToOneSetOpCompetitorUsingCompetitorNameCompetitor)
	t.Run("TargetingToPublisherUsingTargetings", testTargetingToOneSetOpPublisherUsingPublisher)
}

// TestToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneRemove(t *testing.T) {
	t.Run("DpoToUserUsingManagerDpos", testDpoToOneRemoveOpUserUsingManager)
	t.Run("DpoRuleToPublisherUsingDpoRules", testDpoRuleToOneRemoveOpPublisherUsingDpoRulePublisher)
}

// TestOneToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneSet(t *testing.T) {
	t.Run("CompetitorToSellersJSONHistoryUsingCompetitorNameSellersJSONHistory", testCompetitorOneToOneSetOpSellersJSONHistoryUsingCompetitorNameSellersJSONHistory)
}

// TestOneToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneRemove(t *testing.T) {}

// TestToManyAdd tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyAdd(t *testing.T) {
	t.Run("DemandPartnerToDemandParnterPlacements", testDemandPartnerToManyAddOpDemandParnterPlacements)
	t.Run("DpoToDPParentDemandPartnerChildren", testDpoToManyAddOpDPParentDemandPartnerChildren)
	t.Run("DpoToDemandPartnerDemandPartnerConnections", testDpoToManyAddOpDemandPartnerDemandPartnerConnections)
	t.Run("DpoToDemandPartnerDpoRules", testDpoToManyAddOpDemandPartnerDpoRules)
	t.Run("DpoToDemandPartnerPublisherDemands", testDpoToManyAddOpDemandPartnerPublisherDemands)
	t.Run("PublisherToBidCachings", testPublisherToManyAddOpBidCachings)
	t.Run("PublisherToConfiants", testPublisherToManyAddOpConfiants)
	t.Run("PublisherToDpoRules", testPublisherToManyAddOpDpoRules)
	t.Run("PublisherToFactors", testPublisherToManyAddOpFactors)
	t.Run("PublisherToFloors", testPublisherToManyAddOpFloors)
	t.Run("PublisherToPixalates", testPublisherToManyAddOpPixalates)
	t.Run("PublisherToPublisherDemands", testPublisherToManyAddOpPublisherDemands)
	t.Run("PublisherToPublisherDomains", testPublisherToManyAddOpPublisherDomains)
	t.Run("PublisherToRefreshCaches", testPublisherToManyAddOpRefreshCaches)
	t.Run("PublisherToTargetings", testPublisherToManyAddOpTargetings)
	t.Run("UserToManagerDpos", testUserToManyAddOpManagerDpos)
}

// TestToManySet tests cannot be run in parallel
// or deadlocks can occur.
func TestToManySet(t *testing.T) {
	t.Run("PublisherToDpoRules", testPublisherToManySetOpDpoRules)
	t.Run("UserToManagerDpos", testUserToManySetOpManagerDpos)
}

// TestToManyRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyRemove(t *testing.T) {
	t.Run("PublisherToDpoRules", testPublisherToManyRemoveOpDpoRules)
	t.Run("UserToManagerDpos", testUserToManyRemoveOpManagerDpos)
}
