// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// Competitor is an object representing the database table.
type Competitor struct {
	Name     string `boil:"name" json:"name" toml:"name" yaml:"name"`
	URL      string `boil:"url" json:"url" toml:"url" yaml:"url"`
	Type     string `boil:"type" json:"type" toml:"type" yaml:"type"`
	Position int64  `boil:"position" json:"position" toml:"position" yaml:"position"`

	R *competitorR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L competitorL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var CompetitorColumns = struct {
	Name     string
	URL      string
	Type     string
	Position string
}{
	Name:     "name",
	URL:      "url",
	Type:     "type",
	Position: "position",
}

var CompetitorTableColumns = struct {
	Name     string
	URL      string
	Type     string
	Position string
}{
	Name:     "competitors.name",
	URL:      "competitors.url",
	Type:     "competitors.type",
	Position: "competitors.position",
}

// Generated where

type whereHelperint64 struct{ field string }

func (w whereHelperint64) EQ(x int64) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperint64) NEQ(x int64) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperint64) LT(x int64) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperint64) LTE(x int64) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperint64) GT(x int64) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperint64) GTE(x int64) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.GTE, x) }
func (w whereHelperint64) IN(slice []int64) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperint64) NIN(slice []int64) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

var CompetitorWhere = struct {
	Name     whereHelperstring
	URL      whereHelperstring
	Type     whereHelperstring
	Position whereHelperint64
}{
	Name:     whereHelperstring{field: "\"competitors\".\"name\""},
	URL:      whereHelperstring{field: "\"competitors\".\"url\""},
	Type:     whereHelperstring{field: "\"competitors\".\"type\""},
	Position: whereHelperint64{field: "\"competitors\".\"position\""},
}

// CompetitorRels is where relationship names are stored.
var CompetitorRels = struct {
	CompetitorNameSellersJSONHistory string
}{
	CompetitorNameSellersJSONHistory: "CompetitorNameSellersJSONHistory",
}

// competitorR is where relationships are stored.
type competitorR struct {
	CompetitorNameSellersJSONHistory *SellersJSONHistory `boil:"CompetitorNameSellersJSONHistory" json:"CompetitorNameSellersJSONHistory" toml:"CompetitorNameSellersJSONHistory" yaml:"CompetitorNameSellersJSONHistory"`
}

// NewStruct creates a new relationship struct
func (*competitorR) NewStruct() *competitorR {
	return &competitorR{}
}

func (r *competitorR) GetCompetitorNameSellersJSONHistory() *SellersJSONHistory {
	if r == nil {
		return nil
	}
	return r.CompetitorNameSellersJSONHistory
}

// competitorL is where Load methods for each relationship are stored.
type competitorL struct{}

var (
	competitorAllColumns            = []string{"name", "url", "type", "position"}
	competitorColumnsWithoutDefault = []string{"name", "url", "type", "position"}
	competitorColumnsWithDefault    = []string{}
	competitorPrimaryKeyColumns     = []string{"name"}
	competitorGeneratedColumns      = []string{}
)

type (
	// CompetitorSlice is an alias for a slice of pointers to Competitor.
	// This should almost always be used instead of []Competitor.
	CompetitorSlice []*Competitor
	// CompetitorHook is the signature for custom Competitor hook methods
	CompetitorHook func(context.Context, boil.ContextExecutor, *Competitor) error

	competitorQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	competitorType                 = reflect.TypeOf(&Competitor{})
	competitorMapping              = queries.MakeStructMapping(competitorType)
	competitorPrimaryKeyMapping, _ = queries.BindMapping(competitorType, competitorMapping, competitorPrimaryKeyColumns)
	competitorInsertCacheMut       sync.RWMutex
	competitorInsertCache          = make(map[string]insertCache)
	competitorUpdateCacheMut       sync.RWMutex
	competitorUpdateCache          = make(map[string]updateCache)
	competitorUpsertCacheMut       sync.RWMutex
	competitorUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var competitorAfterSelectMu sync.Mutex
var competitorAfterSelectHooks []CompetitorHook

var competitorBeforeInsertMu sync.Mutex
var competitorBeforeInsertHooks []CompetitorHook
var competitorAfterInsertMu sync.Mutex
var competitorAfterInsertHooks []CompetitorHook

var competitorBeforeUpdateMu sync.Mutex
var competitorBeforeUpdateHooks []CompetitorHook
var competitorAfterUpdateMu sync.Mutex
var competitorAfterUpdateHooks []CompetitorHook

var competitorBeforeDeleteMu sync.Mutex
var competitorBeforeDeleteHooks []CompetitorHook
var competitorAfterDeleteMu sync.Mutex
var competitorAfterDeleteHooks []CompetitorHook

var competitorBeforeUpsertMu sync.Mutex
var competitorBeforeUpsertHooks []CompetitorHook
var competitorAfterUpsertMu sync.Mutex
var competitorAfterUpsertHooks []CompetitorHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *Competitor) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range competitorAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *Competitor) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range competitorBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *Competitor) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range competitorAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *Competitor) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range competitorBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *Competitor) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range competitorAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *Competitor) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range competitorBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *Competitor) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range competitorAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *Competitor) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range competitorBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *Competitor) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range competitorAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddCompetitorHook registers your hook function for all future operations.
func AddCompetitorHook(hookPoint boil.HookPoint, competitorHook CompetitorHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		competitorAfterSelectMu.Lock()
		competitorAfterSelectHooks = append(competitorAfterSelectHooks, competitorHook)
		competitorAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		competitorBeforeInsertMu.Lock()
		competitorBeforeInsertHooks = append(competitorBeforeInsertHooks, competitorHook)
		competitorBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		competitorAfterInsertMu.Lock()
		competitorAfterInsertHooks = append(competitorAfterInsertHooks, competitorHook)
		competitorAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		competitorBeforeUpdateMu.Lock()
		competitorBeforeUpdateHooks = append(competitorBeforeUpdateHooks, competitorHook)
		competitorBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		competitorAfterUpdateMu.Lock()
		competitorAfterUpdateHooks = append(competitorAfterUpdateHooks, competitorHook)
		competitorAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		competitorBeforeDeleteMu.Lock()
		competitorBeforeDeleteHooks = append(competitorBeforeDeleteHooks, competitorHook)
		competitorBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		competitorAfterDeleteMu.Lock()
		competitorAfterDeleteHooks = append(competitorAfterDeleteHooks, competitorHook)
		competitorAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		competitorBeforeUpsertMu.Lock()
		competitorBeforeUpsertHooks = append(competitorBeforeUpsertHooks, competitorHook)
		competitorBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		competitorAfterUpsertMu.Lock()
		competitorAfterUpsertHooks = append(competitorAfterUpsertHooks, competitorHook)
		competitorAfterUpsertMu.Unlock()
	}
}

// One returns a single competitor record from the query.
func (q competitorQuery) One(ctx context.Context, exec boil.ContextExecutor) (*Competitor, error) {
	o := &Competitor{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for competitors")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all Competitor records from the query.
func (q competitorQuery) All(ctx context.Context, exec boil.ContextExecutor) (CompetitorSlice, error) {
	var o []*Competitor

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to Competitor slice")
	}

	if len(competitorAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all Competitor records in the query.
func (q competitorQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count competitors rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q competitorQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if competitors exists")
	}

	return count > 0, nil
}

// CompetitorNameSellersJSONHistory pointed to by the foreign key.
func (o *Competitor) CompetitorNameSellersJSONHistory(mods ...qm.QueryMod) sellersJSONHistoryQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"competitor_name\" = ?", o.Name),
	}

	queryMods = append(queryMods, mods...)

	return SellersJSONHistories(queryMods...)
}

// LoadCompetitorNameSellersJSONHistory allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-1 relationship.
func (competitorL) LoadCompetitorNameSellersJSONHistory(ctx context.Context, e boil.ContextExecutor, singular bool, maybeCompetitor interface{}, mods queries.Applicator) error {
	var slice []*Competitor
	var object *Competitor

	if singular {
		var ok bool
		object, ok = maybeCompetitor.(*Competitor)
		if !ok {
			object = new(Competitor)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeCompetitor)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeCompetitor))
			}
		}
	} else {
		s, ok := maybeCompetitor.(*[]*Competitor)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeCompetitor)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeCompetitor))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &competitorR{}
		}
		args[object.Name] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &competitorR{}
			}

			args[obj.Name] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`sellers_json_history`),
		qm.WhereIn(`sellers_json_history.competitor_name in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load SellersJSONHistory")
	}

	var resultSlice []*SellersJSONHistory
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice SellersJSONHistory")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for sellers_json_history")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for sellers_json_history")
	}

	if len(sellersJSONHistoryAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.CompetitorNameSellersJSONHistory = foreign
		if foreign.R == nil {
			foreign.R = &sellersJSONHistoryR{}
		}
		foreign.R.CompetitorNameCompetitor = object
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.Name == foreign.CompetitorName {
				local.R.CompetitorNameSellersJSONHistory = foreign
				if foreign.R == nil {
					foreign.R = &sellersJSONHistoryR{}
				}
				foreign.R.CompetitorNameCompetitor = local
				break
			}
		}
	}

	return nil
}

// SetCompetitorNameSellersJSONHistory of the competitor to the related item.
// Sets o.R.CompetitorNameSellersJSONHistory to related.
// Adds o to related.R.CompetitorNameCompetitor.
func (o *Competitor) SetCompetitorNameSellersJSONHistory(ctx context.Context, exec boil.ContextExecutor, insert bool, related *SellersJSONHistory) error {
	var err error

	if insert {
		related.CompetitorName = o.Name

		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	} else {
		updateQuery := fmt.Sprintf(
			"UPDATE \"sellers_json_history\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, []string{"competitor_name"}),
			strmangle.WhereClause("\"", "\"", 2, sellersJSONHistoryPrimaryKeyColumns),
		)
		values := []interface{}{o.Name, related.CompetitorName}

		if boil.IsDebug(ctx) {
			writer := boil.DebugWriterFrom(ctx)
			fmt.Fprintln(writer, updateQuery)
			fmt.Fprintln(writer, values)
		}
		if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
			return errors.Wrap(err, "failed to update foreign table")
		}

		related.CompetitorName = o.Name
	}

	if o.R == nil {
		o.R = &competitorR{
			CompetitorNameSellersJSONHistory: related,
		}
	} else {
		o.R.CompetitorNameSellersJSONHistory = related
	}

	if related.R == nil {
		related.R = &sellersJSONHistoryR{
			CompetitorNameCompetitor: o,
		}
	} else {
		related.R.CompetitorNameCompetitor = o
	}
	return nil
}

// Competitors retrieves all the records using an executor.
func Competitors(mods ...qm.QueryMod) competitorQuery {
	mods = append(mods, qm.From("\"competitors\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"competitors\".*"})
	}

	return competitorQuery{q}
}

// FindCompetitor retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindCompetitor(ctx context.Context, exec boil.ContextExecutor, name string, selectCols ...string) (*Competitor, error) {
	competitorObj := &Competitor{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"competitors\" where \"name\"=$1", sel,
	)

	q := queries.Raw(query, name)

	err := q.Bind(ctx, exec, competitorObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from competitors")
	}

	if err = competitorObj.doAfterSelectHooks(ctx, exec); err != nil {
		return competitorObj, err
	}

	return competitorObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *Competitor) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no competitors provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(competitorColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	competitorInsertCacheMut.RLock()
	cache, cached := competitorInsertCache[key]
	competitorInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			competitorAllColumns,
			competitorColumnsWithDefault,
			competitorColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(competitorType, competitorMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(competitorType, competitorMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"competitors\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"competitors\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into competitors")
	}

	if !cached {
		competitorInsertCacheMut.Lock()
		competitorInsertCache[key] = cache
		competitorInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the Competitor.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *Competitor) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	competitorUpdateCacheMut.RLock()
	cache, cached := competitorUpdateCache[key]
	competitorUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			competitorAllColumns,
			competitorPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update competitors, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"competitors\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, competitorPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(competitorType, competitorMapping, append(wl, competitorPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update competitors row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for competitors")
	}

	if !cached {
		competitorUpdateCacheMut.Lock()
		competitorUpdateCache[key] = cache
		competitorUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q competitorQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for competitors")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for competitors")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o CompetitorSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), competitorPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"competitors\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, competitorPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in competitor slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all competitor")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *Competitor) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no competitors provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(competitorColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	competitorUpsertCacheMut.RLock()
	cache, cached := competitorUpsertCache[key]
	competitorUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			competitorAllColumns,
			competitorColumnsWithDefault,
			competitorColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			competitorAllColumns,
			competitorPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert competitors, could not build update column list")
		}

		ret := strmangle.SetComplement(competitorAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(competitorPrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert competitors, could not build conflict column list")
			}

			conflict = make([]string, len(competitorPrimaryKeyColumns))
			copy(conflict, competitorPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"competitors\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(competitorType, competitorMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(competitorType, competitorMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert competitors")
	}

	if !cached {
		competitorUpsertCacheMut.Lock()
		competitorUpsertCache[key] = cache
		competitorUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single Competitor record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Competitor) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no Competitor provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), competitorPrimaryKeyMapping)
	sql := "DELETE FROM \"competitors\" WHERE \"name\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from competitors")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for competitors")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q competitorQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no competitorQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from competitors")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for competitors")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o CompetitorSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(competitorBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), competitorPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"competitors\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, competitorPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from competitor slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for competitors")
	}

	if len(competitorAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Competitor) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindCompetitor(ctx, exec, o.Name)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *CompetitorSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := CompetitorSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), competitorPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"competitors\".* FROM \"competitors\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, competitorPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in CompetitorSlice")
	}

	*o = slice

	return nil
}

// CompetitorExists checks if the Competitor row exists.
func CompetitorExists(ctx context.Context, exec boil.ContextExecutor, name string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"competitors\" where \"name\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, name)
	}
	row := exec.QueryRowContext(ctx, sql, name)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if competitors exists")
	}

	return exists, nil
}

// Exists checks if the Competitor row exists.
func (o *Competitor) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return CompetitorExists(ctx, exec, o.Name)
}
