// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testDemandParnterPlacements(t *testing.T) {
	t.Parallel()

	query := DemandParnterPlacements()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testDemandParnterPlacementsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DemandParnterPlacement{}
	if err = randomize.Struct(seed, o, demandParnterPlacementDBTypes, true, demandParnterPlacementColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DemandParnterPlacement struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := DemandParnterPlacements().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testDemandParnterPlacementsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DemandParnterPlacement{}
	if err = randomize.Struct(seed, o, demandParnterPlacementDBTypes, true, demandParnterPlacementColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DemandParnterPlacement struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := DemandParnterPlacements().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := DemandParnterPlacements().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testDemandParnterPlacementsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DemandParnterPlacement{}
	if err = randomize.Struct(seed, o, demandParnterPlacementDBTypes, true, demandParnterPlacementColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DemandParnterPlacement struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := DemandParnterPlacementSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := DemandParnterPlacements().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testDemandParnterPlacementsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DemandParnterPlacement{}
	if err = randomize.Struct(seed, o, demandParnterPlacementDBTypes, true, demandParnterPlacementColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DemandParnterPlacement struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := DemandParnterPlacementExists(ctx, tx, o.DemandPartnerPlacementID)
	if err != nil {
		t.Errorf("Unable to check if DemandParnterPlacement exists: %s", err)
	}
	if !e {
		t.Errorf("Expected DemandParnterPlacementExists to return true, but got false.")
	}
}

func testDemandParnterPlacementsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DemandParnterPlacement{}
	if err = randomize.Struct(seed, o, demandParnterPlacementDBTypes, true, demandParnterPlacementColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DemandParnterPlacement struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	demandParnterPlacementFound, err := FindDemandParnterPlacement(ctx, tx, o.DemandPartnerPlacementID)
	if err != nil {
		t.Error(err)
	}

	if demandParnterPlacementFound == nil {
		t.Error("want a record, got nil")
	}
}

func testDemandParnterPlacementsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DemandParnterPlacement{}
	if err = randomize.Struct(seed, o, demandParnterPlacementDBTypes, true, demandParnterPlacementColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DemandParnterPlacement struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = DemandParnterPlacements().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testDemandParnterPlacementsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DemandParnterPlacement{}
	if err = randomize.Struct(seed, o, demandParnterPlacementDBTypes, true, demandParnterPlacementColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DemandParnterPlacement struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := DemandParnterPlacements().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testDemandParnterPlacementsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	demandParnterPlacementOne := &DemandParnterPlacement{}
	demandParnterPlacementTwo := &DemandParnterPlacement{}
	if err = randomize.Struct(seed, demandParnterPlacementOne, demandParnterPlacementDBTypes, false, demandParnterPlacementColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DemandParnterPlacement struct: %s", err)
	}
	if err = randomize.Struct(seed, demandParnterPlacementTwo, demandParnterPlacementDBTypes, false, demandParnterPlacementColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DemandParnterPlacement struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = demandParnterPlacementOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = demandParnterPlacementTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := DemandParnterPlacements().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testDemandParnterPlacementsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	demandParnterPlacementOne := &DemandParnterPlacement{}
	demandParnterPlacementTwo := &DemandParnterPlacement{}
	if err = randomize.Struct(seed, demandParnterPlacementOne, demandParnterPlacementDBTypes, false, demandParnterPlacementColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DemandParnterPlacement struct: %s", err)
	}
	if err = randomize.Struct(seed, demandParnterPlacementTwo, demandParnterPlacementDBTypes, false, demandParnterPlacementColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DemandParnterPlacement struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = demandParnterPlacementOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = demandParnterPlacementTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := DemandParnterPlacements().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func demandParnterPlacementBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *DemandParnterPlacement) error {
	*o = DemandParnterPlacement{}
	return nil
}

func demandParnterPlacementAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *DemandParnterPlacement) error {
	*o = DemandParnterPlacement{}
	return nil
}

func demandParnterPlacementAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *DemandParnterPlacement) error {
	*o = DemandParnterPlacement{}
	return nil
}

func demandParnterPlacementBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *DemandParnterPlacement) error {
	*o = DemandParnterPlacement{}
	return nil
}

func demandParnterPlacementAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *DemandParnterPlacement) error {
	*o = DemandParnterPlacement{}
	return nil
}

func demandParnterPlacementBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *DemandParnterPlacement) error {
	*o = DemandParnterPlacement{}
	return nil
}

func demandParnterPlacementAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *DemandParnterPlacement) error {
	*o = DemandParnterPlacement{}
	return nil
}

func demandParnterPlacementBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *DemandParnterPlacement) error {
	*o = DemandParnterPlacement{}
	return nil
}

func demandParnterPlacementAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *DemandParnterPlacement) error {
	*o = DemandParnterPlacement{}
	return nil
}

func testDemandParnterPlacementsHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &DemandParnterPlacement{}
	o := &DemandParnterPlacement{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, demandParnterPlacementDBTypes, false); err != nil {
		t.Errorf("Unable to randomize DemandParnterPlacement object: %s", err)
	}

	AddDemandParnterPlacementHook(boil.BeforeInsertHook, demandParnterPlacementBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	demandParnterPlacementBeforeInsertHooks = []DemandParnterPlacementHook{}

	AddDemandParnterPlacementHook(boil.AfterInsertHook, demandParnterPlacementAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	demandParnterPlacementAfterInsertHooks = []DemandParnterPlacementHook{}

	AddDemandParnterPlacementHook(boil.AfterSelectHook, demandParnterPlacementAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	demandParnterPlacementAfterSelectHooks = []DemandParnterPlacementHook{}

	AddDemandParnterPlacementHook(boil.BeforeUpdateHook, demandParnterPlacementBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	demandParnterPlacementBeforeUpdateHooks = []DemandParnterPlacementHook{}

	AddDemandParnterPlacementHook(boil.AfterUpdateHook, demandParnterPlacementAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	demandParnterPlacementAfterUpdateHooks = []DemandParnterPlacementHook{}

	AddDemandParnterPlacementHook(boil.BeforeDeleteHook, demandParnterPlacementBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	demandParnterPlacementBeforeDeleteHooks = []DemandParnterPlacementHook{}

	AddDemandParnterPlacementHook(boil.AfterDeleteHook, demandParnterPlacementAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	demandParnterPlacementAfterDeleteHooks = []DemandParnterPlacementHook{}

	AddDemandParnterPlacementHook(boil.BeforeUpsertHook, demandParnterPlacementBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	demandParnterPlacementBeforeUpsertHooks = []DemandParnterPlacementHook{}

	AddDemandParnterPlacementHook(boil.AfterUpsertHook, demandParnterPlacementAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	demandParnterPlacementAfterUpsertHooks = []DemandParnterPlacementHook{}
}

func testDemandParnterPlacementsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DemandParnterPlacement{}
	if err = randomize.Struct(seed, o, demandParnterPlacementDBTypes, true, demandParnterPlacementColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DemandParnterPlacement struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := DemandParnterPlacements().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testDemandParnterPlacementsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DemandParnterPlacement{}
	if err = randomize.Struct(seed, o, demandParnterPlacementDBTypes, true); err != nil {
		t.Errorf("Unable to randomize DemandParnterPlacement struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(demandParnterPlacementColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := DemandParnterPlacements().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testDemandParnterPlacementToOneDemandPartnerUsingDemandPartner(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local DemandParnterPlacement
	var foreign DemandPartner

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, demandParnterPlacementDBTypes, false, demandParnterPlacementColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DemandParnterPlacement struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, demandPartnerDBTypes, false, demandPartnerColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DemandPartner struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.DemandPartnerID = foreign.DemandPartnerID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.DemandPartner().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.DemandPartnerID != foreign.DemandPartnerID {
		t.Errorf("want: %v, got %v", foreign.DemandPartnerID, check.DemandPartnerID)
	}

	ranAfterSelectHook := false
	AddDemandPartnerHook(boil.AfterSelectHook, func(ctx context.Context, e boil.ContextExecutor, o *DemandPartner) error {
		ranAfterSelectHook = true
		return nil
	})

	slice := DemandParnterPlacementSlice{&local}
	if err = local.L.LoadDemandPartner(ctx, tx, false, (*[]*DemandParnterPlacement)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.DemandPartner == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.DemandPartner = nil
	if err = local.L.LoadDemandPartner(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.DemandPartner == nil {
		t.Error("struct should have been eager loaded")
	}

	if !ranAfterSelectHook {
		t.Error("failed to run AfterSelect hook for relationship")
	}
}

func testDemandParnterPlacementToOneSetOpDemandPartnerUsingDemandPartner(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a DemandParnterPlacement
	var b, c DemandPartner

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, demandParnterPlacementDBTypes, false, strmangle.SetComplement(demandParnterPlacementPrimaryKeyColumns, demandParnterPlacementColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, demandPartnerDBTypes, false, strmangle.SetComplement(demandPartnerPrimaryKeyColumns, demandPartnerColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, demandPartnerDBTypes, false, strmangle.SetComplement(demandPartnerPrimaryKeyColumns, demandPartnerColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*DemandPartner{&b, &c} {
		err = a.SetDemandPartner(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.DemandPartner != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.DemandParnterPlacements[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.DemandPartnerID != x.DemandPartnerID {
			t.Error("foreign key was wrong value", a.DemandPartnerID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.DemandPartnerID))
		reflect.Indirect(reflect.ValueOf(&a.DemandPartnerID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.DemandPartnerID != x.DemandPartnerID {
			t.Error("foreign key was wrong value", a.DemandPartnerID, x.DemandPartnerID)
		}
	}
}

func testDemandParnterPlacementsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DemandParnterPlacement{}
	if err = randomize.Struct(seed, o, demandParnterPlacementDBTypes, true, demandParnterPlacementColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DemandParnterPlacement struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testDemandParnterPlacementsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DemandParnterPlacement{}
	if err = randomize.Struct(seed, o, demandParnterPlacementDBTypes, true, demandParnterPlacementColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DemandParnterPlacement struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := DemandParnterPlacementSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testDemandParnterPlacementsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DemandParnterPlacement{}
	if err = randomize.Struct(seed, o, demandParnterPlacementDBTypes, true, demandParnterPlacementColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DemandParnterPlacement struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := DemandParnterPlacements().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	demandParnterPlacementDBTypes = map[string]string{`DemandPartnerPlacementID`: `character varying`, `DemandPartnerID`: `character varying`, `Name`: `character varying`}
	_                             = bytes.MinRead
)

func testDemandParnterPlacementsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(demandParnterPlacementPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(demandParnterPlacementAllColumns) == len(demandParnterPlacementPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &DemandParnterPlacement{}
	if err = randomize.Struct(seed, o, demandParnterPlacementDBTypes, true, demandParnterPlacementColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DemandParnterPlacement struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := DemandParnterPlacements().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, demandParnterPlacementDBTypes, true, demandParnterPlacementPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize DemandParnterPlacement struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testDemandParnterPlacementsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(demandParnterPlacementAllColumns) == len(demandParnterPlacementPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &DemandParnterPlacement{}
	if err = randomize.Struct(seed, o, demandParnterPlacementDBTypes, true, demandParnterPlacementColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DemandParnterPlacement struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := DemandParnterPlacements().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, demandParnterPlacementDBTypes, true, demandParnterPlacementPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize DemandParnterPlacement struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(demandParnterPlacementAllColumns, demandParnterPlacementPrimaryKeyColumns) {
		fields = demandParnterPlacementAllColumns
	} else {
		fields = strmangle.SetComplement(
			demandParnterPlacementAllColumns,
			demandParnterPlacementPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := DemandParnterPlacementSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testDemandParnterPlacementsUpsert(t *testing.T) {
	t.Parallel()

	if len(demandParnterPlacementAllColumns) == len(demandParnterPlacementPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := DemandParnterPlacement{}
	if err = randomize.Struct(seed, &o, demandParnterPlacementDBTypes, true); err != nil {
		t.Errorf("Unable to randomize DemandParnterPlacement struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert DemandParnterPlacement: %s", err)
	}

	count, err := DemandParnterPlacements().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, demandParnterPlacementDBTypes, false, demandParnterPlacementPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize DemandParnterPlacement struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert DemandParnterPlacement: %s", err)
	}

	count, err = DemandParnterPlacements().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
