// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testRefreshCaches(t *testing.T) {
	t.Parallel()

	query := RefreshCaches()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testRefreshCachesDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RefreshCache{}
	if err = randomize.Struct(seed, o, refreshCacheDBTypes, true, refreshCacheColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RefreshCache struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := RefreshCaches().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testRefreshCachesQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RefreshCache{}
	if err = randomize.Struct(seed, o, refreshCacheDBTypes, true, refreshCacheColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RefreshCache struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := RefreshCaches().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := RefreshCaches().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testRefreshCachesSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RefreshCache{}
	if err = randomize.Struct(seed, o, refreshCacheDBTypes, true, refreshCacheColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RefreshCache struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := RefreshCacheSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := RefreshCaches().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testRefreshCachesExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RefreshCache{}
	if err = randomize.Struct(seed, o, refreshCacheDBTypes, true, refreshCacheColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RefreshCache struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := RefreshCacheExists(ctx, tx, o.RuleID)
	if err != nil {
		t.Errorf("Unable to check if RefreshCache exists: %s", err)
	}
	if !e {
		t.Errorf("Expected RefreshCacheExists to return true, but got false.")
	}
}

func testRefreshCachesFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RefreshCache{}
	if err = randomize.Struct(seed, o, refreshCacheDBTypes, true, refreshCacheColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RefreshCache struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	refreshCacheFound, err := FindRefreshCache(ctx, tx, o.RuleID)
	if err != nil {
		t.Error(err)
	}

	if refreshCacheFound == nil {
		t.Error("want a record, got nil")
	}
}

func testRefreshCachesBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RefreshCache{}
	if err = randomize.Struct(seed, o, refreshCacheDBTypes, true, refreshCacheColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RefreshCache struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = RefreshCaches().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testRefreshCachesOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RefreshCache{}
	if err = randomize.Struct(seed, o, refreshCacheDBTypes, true, refreshCacheColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RefreshCache struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := RefreshCaches().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testRefreshCachesAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	refreshCacheOne := &RefreshCache{}
	refreshCacheTwo := &RefreshCache{}
	if err = randomize.Struct(seed, refreshCacheOne, refreshCacheDBTypes, false, refreshCacheColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RefreshCache struct: %s", err)
	}
	if err = randomize.Struct(seed, refreshCacheTwo, refreshCacheDBTypes, false, refreshCacheColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RefreshCache struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = refreshCacheOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = refreshCacheTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := RefreshCaches().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testRefreshCachesCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	refreshCacheOne := &RefreshCache{}
	refreshCacheTwo := &RefreshCache{}
	if err = randomize.Struct(seed, refreshCacheOne, refreshCacheDBTypes, false, refreshCacheColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RefreshCache struct: %s", err)
	}
	if err = randomize.Struct(seed, refreshCacheTwo, refreshCacheDBTypes, false, refreshCacheColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RefreshCache struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = refreshCacheOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = refreshCacheTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := RefreshCaches().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func refreshCacheBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *RefreshCache) error {
	*o = RefreshCache{}
	return nil
}

func refreshCacheAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *RefreshCache) error {
	*o = RefreshCache{}
	return nil
}

func refreshCacheAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *RefreshCache) error {
	*o = RefreshCache{}
	return nil
}

func refreshCacheBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *RefreshCache) error {
	*o = RefreshCache{}
	return nil
}

func refreshCacheAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *RefreshCache) error {
	*o = RefreshCache{}
	return nil
}

func refreshCacheBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *RefreshCache) error {
	*o = RefreshCache{}
	return nil
}

func refreshCacheAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *RefreshCache) error {
	*o = RefreshCache{}
	return nil
}

func refreshCacheBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *RefreshCache) error {
	*o = RefreshCache{}
	return nil
}

func refreshCacheAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *RefreshCache) error {
	*o = RefreshCache{}
	return nil
}

func testRefreshCachesHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &RefreshCache{}
	o := &RefreshCache{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, refreshCacheDBTypes, false); err != nil {
		t.Errorf("Unable to randomize RefreshCache object: %s", err)
	}

	AddRefreshCacheHook(boil.BeforeInsertHook, refreshCacheBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	refreshCacheBeforeInsertHooks = []RefreshCacheHook{}

	AddRefreshCacheHook(boil.AfterInsertHook, refreshCacheAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	refreshCacheAfterInsertHooks = []RefreshCacheHook{}

	AddRefreshCacheHook(boil.AfterSelectHook, refreshCacheAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	refreshCacheAfterSelectHooks = []RefreshCacheHook{}

	AddRefreshCacheHook(boil.BeforeUpdateHook, refreshCacheBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	refreshCacheBeforeUpdateHooks = []RefreshCacheHook{}

	AddRefreshCacheHook(boil.AfterUpdateHook, refreshCacheAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	refreshCacheAfterUpdateHooks = []RefreshCacheHook{}

	AddRefreshCacheHook(boil.BeforeDeleteHook, refreshCacheBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	refreshCacheBeforeDeleteHooks = []RefreshCacheHook{}

	AddRefreshCacheHook(boil.AfterDeleteHook, refreshCacheAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	refreshCacheAfterDeleteHooks = []RefreshCacheHook{}

	AddRefreshCacheHook(boil.BeforeUpsertHook, refreshCacheBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	refreshCacheBeforeUpsertHooks = []RefreshCacheHook{}

	AddRefreshCacheHook(boil.AfterUpsertHook, refreshCacheAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	refreshCacheAfterUpsertHooks = []RefreshCacheHook{}
}

func testRefreshCachesInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RefreshCache{}
	if err = randomize.Struct(seed, o, refreshCacheDBTypes, true, refreshCacheColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RefreshCache struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := RefreshCaches().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testRefreshCachesInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RefreshCache{}
	if err = randomize.Struct(seed, o, refreshCacheDBTypes, true); err != nil {
		t.Errorf("Unable to randomize RefreshCache struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(refreshCacheColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := RefreshCaches().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testRefreshCacheToOnePublisherUsingRefreshCachePublisher(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local RefreshCache
	var foreign Publisher

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, refreshCacheDBTypes, false, refreshCacheColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RefreshCache struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, publisherDBTypes, false, publisherColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Publisher struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.Publisher = foreign.PublisherID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.RefreshCachePublisher().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.PublisherID != foreign.PublisherID {
		t.Errorf("want: %v, got %v", foreign.PublisherID, check.PublisherID)
	}

	ranAfterSelectHook := false
	AddPublisherHook(boil.AfterSelectHook, func(ctx context.Context, e boil.ContextExecutor, o *Publisher) error {
		ranAfterSelectHook = true
		return nil
	})

	slice := RefreshCacheSlice{&local}
	if err = local.L.LoadRefreshCachePublisher(ctx, tx, false, (*[]*RefreshCache)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.RefreshCachePublisher == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.RefreshCachePublisher = nil
	if err = local.L.LoadRefreshCachePublisher(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.RefreshCachePublisher == nil {
		t.Error("struct should have been eager loaded")
	}

	if !ranAfterSelectHook {
		t.Error("failed to run AfterSelect hook for relationship")
	}
}

func testRefreshCacheToOneSetOpPublisherUsingRefreshCachePublisher(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a RefreshCache
	var b, c Publisher

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, refreshCacheDBTypes, false, strmangle.SetComplement(refreshCachePrimaryKeyColumns, refreshCacheColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, publisherDBTypes, false, strmangle.SetComplement(publisherPrimaryKeyColumns, publisherColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, publisherDBTypes, false, strmangle.SetComplement(publisherPrimaryKeyColumns, publisherColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*Publisher{&b, &c} {
		err = a.SetRefreshCachePublisher(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.RefreshCachePublisher != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.RefreshCaches[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.Publisher != x.PublisherID {
			t.Error("foreign key was wrong value", a.Publisher)
		}

		zero := reflect.Zero(reflect.TypeOf(a.Publisher))
		reflect.Indirect(reflect.ValueOf(&a.Publisher)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.Publisher != x.PublisherID {
			t.Error("foreign key was wrong value", a.Publisher, x.PublisherID)
		}
	}
}

func testRefreshCachesReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RefreshCache{}
	if err = randomize.Struct(seed, o, refreshCacheDBTypes, true, refreshCacheColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RefreshCache struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testRefreshCachesReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RefreshCache{}
	if err = randomize.Struct(seed, o, refreshCacheDBTypes, true, refreshCacheColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RefreshCache struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := RefreshCacheSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testRefreshCachesSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RefreshCache{}
	if err = randomize.Struct(seed, o, refreshCacheDBTypes, true, refreshCacheColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RefreshCache struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := RefreshCaches().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	refreshCacheDBTypes = map[string]string{`Publisher`: `character varying`, `Domain`: `character varying`, `Country`: `character varying`, `Device`: `character varying`, `RefreshCache`: `smallint`, `CreatedAt`: `timestamp without time zone`, `UpdatedAt`: `timestamp without time zone`, `RuleID`: `character varying`, `DemandPartnerID`: `character varying`, `Browser`: `character varying`, `Os`: `character varying`, `PlacementType`: `character varying`, `Active`: `boolean`}
	_                   = bytes.MinRead
)

func testRefreshCachesUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(refreshCachePrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(refreshCacheAllColumns) == len(refreshCachePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &RefreshCache{}
	if err = randomize.Struct(seed, o, refreshCacheDBTypes, true, refreshCacheColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RefreshCache struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := RefreshCaches().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, refreshCacheDBTypes, true, refreshCachePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize RefreshCache struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testRefreshCachesSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(refreshCacheAllColumns) == len(refreshCachePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &RefreshCache{}
	if err = randomize.Struct(seed, o, refreshCacheDBTypes, true, refreshCacheColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RefreshCache struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := RefreshCaches().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, refreshCacheDBTypes, true, refreshCachePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize RefreshCache struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(refreshCacheAllColumns, refreshCachePrimaryKeyColumns) {
		fields = refreshCacheAllColumns
	} else {
		fields = strmangle.SetComplement(
			refreshCacheAllColumns,
			refreshCachePrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := RefreshCacheSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testRefreshCachesUpsert(t *testing.T) {
	t.Parallel()

	if len(refreshCacheAllColumns) == len(refreshCachePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := RefreshCache{}
	if err = randomize.Struct(seed, &o, refreshCacheDBTypes, true); err != nil {
		t.Errorf("Unable to randomize RefreshCache struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert RefreshCache: %s", err)
	}

	count, err := RefreshCaches().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, refreshCacheDBTypes, false, refreshCachePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize RefreshCache struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert RefreshCache: %s", err)
	}

	count, err = RefreshCaches().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
